dist: xenial
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.6"

env:
- DISTRO_TYPE=upstream KIND_VER=v0.7.0 KUBE_VER=v1.17.0 OLM_VER=0.14.1 SDK_VER=v0.16.0

install:


jobs:
  include:
  - stage: Provide path
    name: Provide operator path for Ansible provessing
    script: scripts/ci/provide_path

  - stage: Call ansible script
    name: Execute ansible script with path provided
    script: echo "OP_PATH=$OP_PATH"

