dist: bionic
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.8"

env:
- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_REPO=https://github.com/J0zi/operator-test-playbooks PLAYBOOK_BRANCH=devel-phase-3
#- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_REPO=https://github.com/J0zi/operator-test-playbooks PLAYBOOK_BRANCH=PR/RHO-642-package-and-bundle-tests-v2

services:
  - docker

before_install:
# check-pr needs to be sourced so it can pass the test early.
- source scripts/ci/check-pr $DISTRO_TYPE

install:
  - pip install ansible jmespath
  - ansible-playbook -i localhost, local.yml -e ansible_connection=local -e run_upstream=true  -e run_remove_catalog_repo=false -e kind_version=$KIND_VER -e kind_kube_ver=$KUBE_VER -e olm_ver=$OLM_VER -e operator_sdk_version=$SDK_VER --tags host_build

jobs:
  include:
  - stage: Test Pipeline
    script:
    - scripts/ci/run-ansible-tests
  - stage: Release Pipeline
    script:
    - scripts/ci/run-release-upstream
#TODO:uncomment
#    if: type = push
