dist: xenial
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.8"

env:
- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_IMAGE=quay.io/j0zi/operator-test-playbooks

services:
  - docker

install:
  - pip3 install ansible

jobs:
  include:
  - stage: Integration Tests
    before_script:
    - ansible-pull -U https://github.com/J0zi/operator-test-playbooks -C PR/RHO-642-package-and-bundle-tests-v2 -i localhost, -e kind_version=$KIND_VER -e kind_kube_ver=$KUBE_VER --tags host_build -e ansible_distribution=Ubuntu -e ansible_user_id=travis
    - kind get kubeconfig --name operator-test > ~/.kube/config
    - docker run -d -it --name playbook --net host -v ~/.kube:/root/.kube -v $(pwd):/tmp/community-operators-for-catalog $PLAYBOOK_IMAGE
#    - pip install --upgrade pyyaml

    script:
    - scripts/ci/run-ansible-tests
