dist: bionic
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.8"

env:
- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_REPO=https://github.com/J0zi/operator-test-playbooks PLAYBOOK_BRANCH=PR/RHO-642-package-and-bundle-tests-v2
#- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_REPO=https://github.com/J0zi/operator-test-playbooks PLAYBOOK_BRANCH=testing-pr-27-ecosystem

#services:
#  - docker

before_install:
# check-pr needs to be sourced so it can pass the test early.
- source scripts/ci/check-pr $DISTRO_TYPE

install:
  - pip install ansible
  # - scripts/ci/upgrade-docker

jobs:
  include:
  - stage: Integration Tests
    # before_script:
    # - ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH -i localhost, -e run_upstream=true -e kind_version=$KIND_VER -e kind_kube_ver=$KUBE_VER --tags host_build --skip-tags always
    # - kind get kubeconfig --name operator-test > ~/.kube/config
    # - docker version
    # - docker run -d -it --name playbook --net host -v ~/.kube:/root/.kube -v $(pwd):/tmp/community-operators-for-catalog $PLAYBOOK_IMAGE


    script:
    - scripts/ci/run-ansible-tests
