AUTOMERGE_ENABLED: 1
OP_TEST_CONTAINER_OPT: "-t"
SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/iss.sh"
GODEBUG: x509ignoreCN=0
OP_TEST_INDEX_MIRROR: 1
OP_TEST_MIRROR_LATEST_TAG: "v4.6"
QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP: ${{ secrets.QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP }}
QUAY_API_TOKEN_OPERATORHUBIO: ${{ secrets.QUAY_API_TOKEN_OPERATORHUBIO }}
QUAY_RH_INDEX_PW: ${{ secrets.QUAY_RH_INDEX_PW }}
IIB_INPUT_REGISTRY_TOKEN: ${{ secrets.IIB_INPUT_REGISTRY_TOKEN }}
IIB_OUTPUT_REGISTRY_TOKEN: ${{ secrets.IIB_OUTPUT_REGISTRY_TOKEN }}
OP_TEST_DEBUG: 99 # TEST TEST original value 1
OP_TEST_CONTAINER_OPT: "-t"
OP_TEST_SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/test.sh"
ISS_SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/iss.sh"
OP_TEST_IMAGE: "quay.io/operator_testing/operator-test-playbooks:latest"
OP_TEST_PROD: 1
OP_TEST_INDEX_MIRROR: 0
OP_TEST_MIRROR_LATEST_TAG: "v4.6"
GODEBUG: x509ignoreCN=0
CI_OHIO_TRIGGER_TOKEN: ${{ secrets.CI_OHIO_TRIGGER_TOKEN }}
OHIO_REGISTRY_TOKEN: ${{ secrets.OHIO_REGISTRY_TOKEN }}
QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP: ${{ secrets.QUAY_API_TOKEN_OPENSHIFT_COMMUNITY_OP }}
QUAY_API_TOKEN_OPERATORHUBIO: ${{ secrets.QUAY_API_TOKEN_OPERATORHUBIO }}
QUAY_APPREG_TOKEN: ${{ secrets.QUAY_APPREG_TOKEN }}
QUAY_COURIER_TOKEN: ${{ secrets.QUAY_COURIER_TOKEN }}
QUAY_RH_INDEX_PW: ${{ secrets.QUAY_RH_INDEX_PW }}
REPO_GHA_PAT: ${{ secrets.REPO_GHA_PAT }}
OP_TEST_DEBUG: 1
OP_TEST_CONTAINER_OPT: "-t"
OP_TEST_SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/test.sh"
OP_TEST_IMAGE: "quay.io/operator_testing/operator-test-playbooks:latest"
OP_TEST_PROD: 0
OP_TEST_DRY_RUN: 0
KIND_KUBE_VERSION: v1.21.1
