#!/bin/bash
#TODO: handle in case of community-operators

set -e

unset OP_PATH
unset OP_VER
[ -e /tmp/op_ver ] && rm /tmp/op_ver

declare -A OP_TYPES
OP_TYPES=(
  ["upstream"]="upstream-community-operators"
  ["openshift"]="community-operators"
)
DIR="$(cd "$(dirname ${BASH_SOURCE[0]})" && pwd)"

for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
  . "$f"
done

# Remove duplicates.
declare -A SEEN
for op_distro in "${!OP_TYPES[@]}"; do
  OP_TYPE_VAR="OPERATORS_${op_distro^^}"
  declare $OP_TYPE_VAR=""
  for op_type in ${OP_TYPES[$op_distro]}; do
    for file in $(git diff master --name-only 2>&1); do
      # Run on operator packages with file deletions but still exist.
      if [[ ! -e "$file" && ! -d "$(dirname "$file")" ]]; then
        continue
      fi
      if echo "$file" | grep -q "^$op_type"; then
        OP_PATH="$(echo "$file" | awk -F'/' '{ print $1"/"$2 }')"
        OP_VER="$(echo "$file" | awk -F'/' '{ print $3 }')"
        echo $OP_VER >> /tmp/op_ver
        if [[ -n "${SEEN[$OP_PATH]}" ]]; then
          continue
        fi
        SEEN[$OP_PATH]="seen"
      fi
    done
  done
done

export OP_VER=$(cat /tmp/op_ver|  sort --version-sort | tail -n 1)
export OP_PATH=$OP_PATH