#!/usr/bin/env bash
set -e

DIRS=()

PR_COMMIT=$(git log -n2 --format=format:"%H" | tail -n 1)

if [[ "$1" == "openshift" ]]; then
  DIRS=( "community-operators" )
else
  DIRS=( "upstream-community-operators" )
fi

GIT_INFO=master
IS_TESTABLE=0

#Force build after merge
if [[ $(git diff --name-only master |wc -l) -eq 0 ]]; then
  export IS_TESTABLE=$(echo $IS_TESTABLE)
fi

# Only run CI on changes to certain directories.
if git log -m -1 --name-only --first-parent $PR_COMMIT | grep -q '\.yaml'; then
  for d in "${DIRS[@]}"; do
    if git log -m -1 --name-only --first-parent $PR_COMMIT | grep -q "$d"; then
      IS_TESTABLE=1
      break
    fi
  done
  if [[ $IS_TESTABLE -eq 0 ]]; then
     echo "No testable operators or scripts were updated, not running the CI."
     exit 0
  fi
fi
