#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)
git log|head -n 100
echo "$TRAVIS_COMMIT"
echo "Diffs detected:"
git log -m -1 --name-only --first-parent $TRAVIS_COMMIT


if [ -n "${OP_PATH}" ];
  then
    echo "Found modified operator. Green light."
    exit 0
  else
    echo "Operator not modified, no need to run tests. Red light."
    exit 1
fi
