#!/bin/bash

set -e

unset OP_PATH
unset OP_VER

declare -A OP_TYPES
OP_TYPES=(
  ["upstream"]="upstream-community-operators"
  ["openshift"]="community-operators"
)
DIR="$(cd "$(dirname ${BASH_SOURCE[0]})" && pwd)"

for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
  . "$f"
done

# Remove duplicates.
declare -A SEEN
for op_distro in "${!OP_TYPES[@]}"; do
  OP_TYPE_VAR="OPERATORS_${op_distro^^}"
  declare $OP_TYPE_VAR=""
  for op_type in ${OP_TYPES[$op_distro]}; do
    for file in $(git diff master --name-only 2>&1); do
      # Run on operator packages with file deletions but still exist.
      if [[ ! -e "$file" && ! -d "$(dirname "$file")" ]]; then
        continue
      fi
      if echo "$file" | grep -q "^$op_type"; then
        OP_PATH="$(echo "$file" | awk -F'/' '{ print $1"/"$2 }')"
        if [[ -n "${SEEN[$OP_PATH]}" ]]; then
          continue
        fi
        SEEN[$OP_PATH]="seen"
      fi
    done
  done
  echo "export OP_PATH=$OP_PATH"
  echo "export OP_VER=$OP_VER"
done