#!/usr/bin/env bash

if [ $(git diff master --name-only 2>&1|wc -l) -gt 0 ] ;
  then
    echo "Release pipeline not running for PR, found modified operator."
    exit 0
  fi

echo "Release pipeline starting"
rm /tmp/changed-git* 2>/dev/null
pwd
ls
mkdir -p /tmp/oper
cd /tmp/oper
git clone --depth=50 -n https://github.com/operator-framework/community-operators.git
cd community-operators
git log --pretty=format: --name-only --since="3 days ago" | sort | uniq > /tmp/changed-git-files
grep upstream-community-operators /tmp/changed-git-files > /tmp/changed-git-files-upstream
if [ -f /tmp/changed-git-files-upstream ]; then
    awk -F 'upstream-community-operators/' '{ print $2 }' /tmp/changed-git-files-upstream > /tmp/changed-git-files-upstream-list
    awk -F '/' '{ print $1 }' /tmp/changed-git-files-upstream-list|sort|uniq > /tmp/changed-git-files-upstream-opnames
    sed 's/^/- /' /tmp/changed-git-files-upstream-opnames > /tmp/changed-operators.yaml
    sed -i "1ioperator_base_dir: /tmp/community-operators-for-catalog/upstream-community-operators\noperators:" /tmp/changed-operators.yaml
    CHANGED_OPERATORS=`cat /tmp/changed-operators.yaml`
else
    CHANGED_OPERATORS=''
fi
echo "execute ansible on following"
echo "$CHANGED_OPERATORS"