#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

#docker exec -it playbook ansible-playbook -vv -i host.docker.internal, local.yml --ssh-common-args='-o StrictHostKeyChecking=no' -e run_upstream=$RUN_UPSTREAM -e operator_dir=/tmp/community-operators-for-catalog/$OP_PATH -e operator_version=$OP_VER --tags pure-test
docker exec -it playbook ansible-playbook -vv -i 127.0.0.1, local.yml --ssh-common-args='-o StrictHostKeyChecking=no' -e run_upstream=$RUN_UPSTREAM -e operator_dir=/tmp/community-operators-for-catalog/$OP_PATH -e operator_version=$OP_VER --tags pure-test
