#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

echo "RUN_UPSTREAM=$RUN_UPSTREAM"
docker exec -it playbook ansible-playbook -vv -i localhost, local.yml -e ansible_connection=local -e run_upstream=$RUN_UPSTREAM -e operator_dir=/tmp/community-operators-for-catalog/$OP_PATH -e operator_version=$OP_VER --tags pure-test
