#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

if [ -n "${OP_PATH}" ] ;
  then
    echo "Release pipeline not running for PR, found modified operator."
    exit 0
  fi

echo "here will be release pipeline"
