#!/usr/bin/env bash

eval $(scripts/ci/ansible-env)

if [ -z "${OP_PATH}" ] ;
  then
    echo "No operator modification detected. Exiting."
    exit 0
  else
    echo "Testing pipeline functionality on a sample operator"
  fi

ansible-pull -U $PLAYBOOK_REPO -C $PLAYBOOK_BRANCH -i localhost, local.yml -e ansible_connection=local \
-e run_upstream=$RUN_UPSTREAM  \
-e kind_version=$KIND_VER -e kind_kube_ver=$KUBE_VER -e olm_ver=$OLM_VER -e operator_sdk_version=$SDK_VER \
-e operator_dir=$(pwd)/upstream-community-operators/ripsaw -e operator_version=0.1.0 -e run_remove_catalog_repo=false -e catalog_repo_dir=$(pwd)
