name: Report Openshift status

on:
  repository_dispatch:
    types:
      - manual-openshift-report
      - openshift-test-status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Setting Openshift deployment status"
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context.payload.client_payload.source_pr)
            github.issues.addLabels({
              issue_number: context.payload.client_payload.source_pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'deployment-ok' ]
            })
#      - name: "Setting Openshift deployment status"
#        uses: actions/github-script@v3
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            github.issues.addLabels({
#              issue_number: 130,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              labels: [ 'deployment-ok' ]
#            })